version: '3'
services:
  mysql:
   image: mysql:5.7
   ports:
     - '3306:3306'
   volumes:
     - mysqldata:/var/lib/mysql
     - ./initdb:/docker-entrypoint-initdb.d
   container_name: mysql
   environment:
    MYSQL_ROOT_PASSWORD: root
    TZ: Asia/Tehran



volumes:
  mysqldata:
   driver: local